version: '3.8'

services:

  # _____   API   _____ #

  api:
    container_name: "app"
    image: "app_image"
    environment:
      - NODE_ENV:${NODE_ENV}

    build:
      context: ./app
      target: "${NODE_ENV}"
      dockerfile: Dockerfile

    # entrypoint: [ "npm", "run", "start:${NODE_ENV}"]

    env_file:
      - .env

    links:
      - postgres:postgres

    depends_on:
      - postgres

    ports:
      - 5555:5555
    
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

    networks:
      - nesjs-network

    restart: unless-stopped





  # _____   DB Postgres  _____ #

  postgres:
    container_name: postgres
    image: postgres:15-bullseye

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: "${POSTGRES_DB_PREFIX}_${POSTGRES_DB_NAME}"
      PG_DATA: /var/lib/postgresql/data

    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}

    volumes:
     - ./pgdata/data:/var/lib/postgresql/data

    networks:
      - nesjs-network

    restart: on-failure



  # _____   PG Admin   _____ #
  
  pgadmin:
    links:
      - postgres:postgres

    container_name: pgadmin
    image: dpage/pgadmin4

    env_file:
      - .env

    ports:
      - ${PGADMIN_PORT}:80

    volumes:
      - ./pgdata/pgadmin:/root/.pgadmin

    networks:
      - nesjs-network




  # _____   Nginx   _____ #

  nginx:
    image: nginx:stable-alpine
    container_name: nginx

    depends_on:
      - api
      - postgres
      - pgadmin

    environment:
      - NGINX_PORT=${NGINX_PORT}
      - BACKEND_PORT=${BACKEND_PORT}

    ports:
      - 80:${NGINX_PORT}

    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      - nesjs-network




networks:
  nesjs-network: